name: Client push master
on: 
  push:
    paths:
      - client/*
      - client/*/*
      - client/*/*/*
      - client/*/*/*/*
      - client/*/*/*/*/*
      - client/*/*/*/*/*/*
      - client/*/*/*/*/*/*/*
      - client/*/*/*/*/*/*/*/*
      - client/*/*/*/*/*/*/*/*/*
      - client/*/*/*/*/*/*/*/*/*/*

jobs:
  test:
    name: Running client tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build -t aharandi/react-test -f ./client/Dockerfile.dev ./client
      - name: Run tests in Docker image
        run: docker run -e CI=true aharandi/react-test npm test

  deploy:
    name: Build, push and deploy the Docker image to Kubernetes cluster
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Build client image
        run: docker build -t aharandi/multi-client:${{ github.sha }} ./client
      - name: Pushing image to docker hub
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

          docker push aharandi/multi-client:${{ github.sha }}
      - name: Get kubeconfig
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        uses: ./.github/actions/get-kubeconfig
      - name: Deploying to Kubernetes cluster
        uses: steebchen/kubectl@master
        with:
          entrypoint: /bin/sh
          args: -c "kubectl set image deployment/client-deployment client=aharandi/multi-client:${{ github.sha }}"
