name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t aharandi/react-test -f ./client/Dockerfile.dev ./client
      run: docker run -e CI=true aharandi/react-test npm test

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t aharandi/multi-client ./client
      run: docker build -t aharandi/multi-nginx ./nginx
      run: docker build -t aharandi/multi-server ./server
      run: docker build -t aharandi/multi-worker ./worker
      
  push:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker push aharandi/multi-client
      run: docker push aharandi/multi-nginx
      run: docker push aharandi/multi-server
      run: docker push aharandi/multi-worker
