name: Server pull request master
on: 
  pull_request:
    paths:
      - server/*
      - server/*/*
      - server/*/*/*
      - server/*/*/*/*
      - server/*/*/*/*/*
      - server/*/*/*/*/*/*
      - server/*/*/*/*/*/*/*
      - server/*/*/*/*/*/*/*/*
      - server/*/*/*/*/*/*/*/*/*
      - server/*/*/*/*/*/*/*/*/*/*

jobs:
  build:
    name: Build and push the Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build server image
        run: docker build -t aharandi/multi-server:${{ github.sha }} -t aharandi/multi-server:latest ./server
      - name: Pushing image to docker hub
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
          docker push aharandi/multi-server:${{ github.sha }}
          docker push aharandi/multi-server:latest

