name: Server push master
on: 
  push:
    paths:
      - server/*
      - server/*/*
      - server/*/*/*
      - server/*/*/*/*
      - server/*/*/*/*/*
      - server/*/*/*/*/*/*
      - server/*/*/*/*/*/*/*
      - server/*/*/*/*/*/*/*/*
      - server/*/*/*/*/*/*/*/*/*
      - server/*/*/*/*/*/*/*/*/*/*

jobs:
  deploy:
    name: Build, push and deploy the Docker image to Kubernetes cluster
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Build server image
        run: docker build -t aharandi/multi-server:${{ github.sha }} ./server
      - name: Pushing image to docker hub
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
          docker push aharandi/multi-server:${{ github.sha }}
      - name: Deploying to Kubernetes cluster
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        uses: ./.github/actions/kubectl
        with:
          args: set image deployment/server-deployment server=aharandi/multi-server:${{ github.sha }}
