name: Server Test
on:
  push:
    paths:
      - test/*
      - test/*/*
      - test/*/*/*
      - test/*/*/*/*
      - test/*/*/*/*/*
      - test/*/*/*/*/*/*
      - test/*/*/*/*/*/*/*
      - test/*/*/*/*/*/*/*/*
      - test/*/*/*/*/*/*/*/*/*
      - test/*/*/*/*/*/*/*/*/*/*

jobs:
  deploy:
    name: Build, push and deploy the Docker image to Kubernetes cluster
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Getting kubeconfig
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        uses: digitalocean/action-doctl@master
        with:
          args: kubernetes cluster kubeconfig show $CLUSTER_NAME > $GITHUB_WORKSPACE/.kubeconfig
      - name: cat
        run: cat ${GITHUB_WORKSPACE}/.kubeconfig
      - name: Deploying to Kubernetes cluster
        env:
          KUBECONFIG: ${GITHUB_WORKSPACE}/.kubeconfig
        uses: docker://lachlanevenson/k8s-kubectl
        with:
          args: --kubeconfig $GITHUB_WORKSPACE/.kubeconfig config view
