name: Worker master
on:
  push:
    paths:
      - worker/*
      - worker/*/*
      - worker/*/*/*
      - worker/*/*/*/*
      - worker/*/*/*/*/*
      - worker/*/*/*/*/*/*
      - worker/*/*/*/*/*/*/*
      - worker/*/*/*/*/*/*/*/*
      - worker/*/*/*/*/*/*/*/*/*
      - worker/*/*/*/*/*/*/*/*/*/*

jobs:
  build:
    name: Build and publish the Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build worker image
        run: docker build -t aharandi/multi-worker:${{ github.sha }} -t aharandi/multi-worker:latest ./worker
      - name: Pushing image to docker hub
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
          docker push aharandi/multi-worker:${{ github.sha }}
          docker push aharandi/multi-worker:latest
  deploy:
    name: Deploy docker image to Kubernetes cluster
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Getting kubeconfig
        if: github.event_name == 'push'
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        uses: digitalocean/action-doctl@master
        with:
          args: kubernetes cluster kubeconfig show $CLUSTER_NAME > /github/workspace/config
      - name: Deploying to Kubernetes cluster
        if: github.event_name == 'push'
        env:
          KUBECONFIG: /github/workspace/config
        uses: docker://lachlanevenson/k8s-kubectl
        with:
          args: set image deployment/worker-deployment worker=aharandi/multi-worker:${{ github.sha }}
