name: Worker pull request master
on: 
  pull_request:
    paths:
      - worker/*
      - worker/*/*
      - worker/*/*/*
      - worker/*/*/*/*
      - worker/*/*/*/*/*
      - worker/*/*/*/*/*/*
      - worker/*/*/*/*/*/*/*
      - worker/*/*/*/*/*/*/*/*
      - worker/*/*/*/*/*/*/*/*/*
      - worker/*/*/*/*/*/*/*/*/*/*

jobs:
  deploy:
    name: Build, push and deploy the Docker image to Kubernetes cluster
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Build worker image
        run: docker build -t aharandi/multi-worker:${{ github.sha }} ./worker
      - name: Pushing image to docker hub
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
          docker push aharandi/multi-worker:${{ github.sha }}
      - name: Deploying to Kubernetes cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image deployment/worker-deployment worker=aharandi/multi-worker:${{ github.sha }}
